---
abstract: 'Blah blah blah'
author:
  - 'Scott Kiehn E<lt>sk.keenlinks@gmail.comE<gt>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.013, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-TimeMoment
provides:
  Mojolicious::Plugin::TimeMoment:
    file: lib/Mojolicious/Plugin/TimeMoment.pm
    version: '0.05'
requires:
  Mojolicious: '6.20'
  Time::Moment: '0.38'
  Time::y2038: '20100403'
  perl: '5.008001'
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
